apiVersion: v1
kind: Service
metadata:
  name: ftgo-customer-service
  namespace: default
spec:
  ports:
  - port: 8082
    targetPort: 8080
  selector:
    svc: ftgo-customer-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftgo-customer-service
  labels:
    application: ftgo
spec:
  selector:
    matchLabels:
      svc: ftgo-customer-service
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        svc: ftgo-customer-service
    spec:
      containers:
      - name: ftgo-customer-service
        image: eventuateexamples/eventuate-tram-examples-customers-and-orders-customer-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: httpport
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://ftgo-mysql/eventuate
          - name: SPRING_DATASOURCE_USERNAME
            value: mysqluser
          - name: SPRING_DATASOURCE_PASSWORD
            value: mysqlpw
          - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            value: com.mysql.jdbc.Driver
          - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
            value: ftgo-kafka:9092
          - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
            value: ftgo-zookeeper:2181
          - name: CDC_SERVICE_URL
            value: http://ftgo-cdc-service:8080
          - name: SPRING_SLEUTH_ENABLED
            value: "true"
          - name: SPRING_SLEUTH_SAMPLER_PROBABILITY
            value: "1"
          - name: SPRING_ZIPKIN_BASE_URL
            value: http://zipkin:9411/
        livenessProbe:
          httpGet:
            path: /actuator
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
---