apiVersion: v1
kind: Service
metadata:
  name: ftgo-zipkin
  namespace: default
spec:
  ports:
  - port: 9411
    targetPort: 9411
  selector:
    svc: ftgo-zipkin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftgo-zipkin
  labels:
    application: ftgo
spec:
  selector:
    matchLabels:
      svc: ftgo-zipkin
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        svc: ftgo-zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:2.21
        imagePullPolicy: Always
        ports:
        - containerPort: 9411
          name: httpport
        env:
          - name: JAVA_OPTS
            value: "-Xmx64m"
        livenessProbe:
          httpGet:
            path: /health
            port: 9411
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 9411
          initialDelaySeconds: 60
          periodSeconds: 20
---