version: '3'
services:
  orderhistorytextsearchservice:
    build: ./order-history-text-search-service/
    ports:
      - "8084:8080"
    depends_on:
      - kafka
      - zookeeper
      - elasticsearch
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9300

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      - http.host=0.0.0.0
      - network.publish_host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
