version: '3'
services:
  jmeterservice:
    build:
      context: ./jmeter-service/
    image: eventuateexamples/eventuate-tram-examples-customers-and-orders-jmeter-service
    ports:
      - "8084:8080"
    environment:
      JMETER_SERVICE_RESULTS_FOLDER: /usr/local/results
      JMETER_SERVICE_TESTPLAN_FOLDER: /usr/local/plans
      JMETER_PATH: /usr/local/apache-jmeter-5.2.1/bin/jmeter
