apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: eventuate-tram-examples-customers-and-orders
deploy:
  kubectl:
    manifests:
      - deployment/kubernetes/infrastructure-services/*
      - deployment/kubernetes/application-services/*
    flags:
      apply: [ "--namespace", "eventuate-tram-examples-customers-and-orders" ]
  statusCheckDeadlineSeconds: 600

profiles:
  - name: local
    deploy:
      kubectl:
        manifests:
          - deployment/kubernetes/namespace/*
          - deployment/kubernetes/secrets/*
          - deployment/kubernetes/infrastructure-services/*
          - deployment/kubernetes/application-services/*
  - name: aks
    deploy:
      kubectl:
        manifests:
          - deployment/kubernetes/infrastructure-services/*
          - deployment/kubernetes/application-services/*
