apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: eventuate-tram-examples-customers-and-orders
deploy:
  kubectl:
    manifests:
      - deployment/kubernetes/yaml/*
    flags:
      apply: [ "--namespace", "eventuate-tram-examples-customers-and-orders" ]
  statusCheckDeadlineSeconds: 180