version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-tram-examples-customers-and-orders
    steps:
      - checkout
      - run:
          command: .circleci/install-jdk-14.sh
      - restore_cache:
          keys:
            - eventuate-tram-examples-customers-and-orders-{{ checksum "gradle.properties" }}-{{ checksum "pom.xml" }}
            - eventuate-tram-examples-customers-and-orders-
      - run:
          command: |
            ./.circleci/upgrade-docker-compose.sh
            . ./.circleci/setenv-circle-ci.sh
            ./gradlew testClasses
            ./mvnw package test-compile -DskipTests
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: eventuate-tram-examples-customers-and-orders-{{ checksum "gradle.properties" }}-{{ checksum "pom.xml" }}
      - run:
          command: |
            . ./.circleci/setenv-circle-ci.sh
            ./build-and-test-snapshots.sh
      - run:
          command: |
            . ./.circleci/setenv-circle-ci.sh
            ./build-and-test-all-mysql-binlog.sh
      - run:
          command: |
            . ./.circleci/setenv-circle-ci.sh
            ./build-and-test-all-postgres-polling.sh
      - run:
          command: |
            . ./.circleci/setenv-circle-ci.sh
            ./build-and-test-all-postgres-wal.sh
      - run:
          command: |
            . ./.circleci/setenv-circle-ci.sh
            ./build-and-test-all-mysql-maven.sh
      - run:
          command: |
            . ./.circleci/setenv-circle-ci.sh
            ./publish-docker-images.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - run:
          name: Print container logs
          command: |
            export TERM=dumb
            ./.circleci/print-container-logs.sh
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - store_artifacts:
          path: ~/container-logs
